# application configuration
logging:
  level:
    root: DEBUG
    org:
      hibernate: INFO
      hibernate.SQL: DEBUG
      hibernate.cache: DEBUG
      hibernate.stat: DEBUG

# datasource configuration
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${DATABASE_NAME:song_service}
    username: ${POSTGRES_USERNAME:microservice_foundation}
    password: ${POSTGRES_PASSWORD:microservice_foundation}
    driver-class-name: org.postgresql.Driver
    maxIdle: 30
    maxWait: 10000
    maxActive: 100
  jpa.hibernate.ddl-auto: create-drop
  database-platform: org.hibernate.dialect.PostgreSQLDialect