# application configuration
application:
  database:
    host: ${DB_HOST}
    port: ${DB_PORT}
    name: ${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  error:
    whitelabel:
      enabled: true
    include-message: always
    include-stacktrace: never

# datasource configuration
spring:
  r2dbc:
    url: r2dbc:postgresql://${application.database.host}:${application.database.port}/${application.database.name}
    username: ${application.database.username}
    password: ${application.database.password}
    initialization-mode: always
    pool:
      enabled: true
      initial-size: 5
      max-size: 10

# cloud configuration
aws:
  s3:
    endpoint: ${AWS_S3_URL:https://s3.amazonaws.com/}
    maxRetry: 3